/**
 * Ukrainian words for Alias game
 * Sorted by difficulty: 1 = Easy, 2 = Medium, 3 = Hard
 * Categories: animals, food, professions, objects, actions, nature, abstract, body, clothes, transport, sports, culture
 */

export const ukrainianWords = [
  // ========================================
  // LEVEL 1 — EASY (~700 words)
  // Common everyday words, concrete nouns
  // ========================================

  // Animals (тварини)
  { word: "кішка", difficulty: 1, category: "тварини" },
  { word: "собака", difficulty: 1, category: "тварини" },
  { word: "корова", difficulty: 1, category: "тварини" },
  { word: "кінь", difficulty: 1, category: "тварини" },
  { word: "свиня", difficulty: 1, category: "тварини" },
  { word: "курка", difficulty: 1, category: "тварини" },
  { word: "риба", difficulty: 1, category: "тварини" },
  { word: "птах", difficulty: 1, category: "тварини" },
  { word: "заєць", difficulty: 1, category: "тварини" },
  { word: "вовк", difficulty: 1, category: "тварини" },
  { word: "лисиця", difficulty: 1, category: "тварини" },
  { word: "ведмідь", difficulty: 1, category: "тварини" },
  { word: "миша", difficulty: 1, category: "тварини" },
  { word: "жаба", difficulty: 1, category: "тварини" },
  { word: "метелик", difficulty: 1, category: "тварини" },
  { word: "черепаха", difficulty: 1, category: "тварини" },
  { word: "равлик", difficulty: 1, category: "тварини" },
  { word: "павук", difficulty: 1, category: "тварини" },
  { word: "бджола", difficulty: 1, category: "тварини" },
  { word: "муха", difficulty: 1, category: "тварини" },
  { word: "комар", difficulty: 1, category: "тварини" },
  { word: "слон", difficulty: 1, category: "тварини" },
  { word: "лев", difficulty: 1, category: "тварини" },
  { word: "тигр", difficulty: 1, category: "тварини" },
  { word: "мавпа", difficulty: 1, category: "тварини" },
  { word: "крокодил", difficulty: 1, category: "тварини" },
  { word: "дельфін", difficulty: 1, category: "тварини" },
  { word: "кит", difficulty: 1, category: "тварини" },
  { word: "олень", difficulty: 1, category: "тварини" },
  { word: "їжак", difficulty: 1, category: "тварини" },
  { word: "білка", difficulty: 1, category: "тварини" },
  { word: "голуб", difficulty: 1, category: "тварини" },
  { word: "ворона", difficulty: 1, category: "тварини" },
  { word: "горобець", difficulty: 1, category: "тварини" },
  { word: "качка", difficulty: 1, category: "тварини" },
  { word: "гусак", difficulty: 1, category: "тварини" },
  { word: "папуга", difficulty: 1, category: "тварини" },
  { word: "акула", difficulty: 1, category: "тварини" },
  { word: "змія", difficulty: 1, category: "тварини" },
  { word: "черв'як", difficulty: 1, category: "тварини" },

  // Food (їжа)
  { word: "хліб", difficulty: 1, category: "їжа" },
  { word: "молоко", difficulty: 1, category: "їжа" },
  { word: "яблуко", difficulty: 1, category: "їжа" },
  { word: "банан", difficulty: 1, category: "їжа" },
  { word: "апельсин", difficulty: 1, category: "їжа" },
  { word: "помідор", difficulty: 1, category: "їжа" },
  { word: "огірок", difficulty: 1, category: "їжа" },
  { word: "картопля", difficulty: 1, category: "їжа" },
  { word: "морква", difficulty: 1, category: "їжа" },
  { word: "цибуля", difficulty: 1, category: "їжа" },
  { word: "часник", difficulty: 1, category: "їжа" },
  { word: "капуста", difficulty: 1, category: "їжа" },
  { word: "масло", difficulty: 1, category: "їжа" },
  { word: "сир", difficulty: 1, category: "їжа" },
  { word: "яйце", difficulty: 1, category: "їжа" },
  { word: "м'ясо", difficulty: 1, category: "їжа" },
  { word: "цукерка", difficulty: 1, category: "їжа" },
  { word: "торт", difficulty: 1, category: "їжа" },
  { word: "морозиво", difficulty: 1, category: "їжа" },
  { word: "печиво", difficulty: 1, category: "їжа" },
  { word: "суп", difficulty: 1, category: "їжа" },
  { word: "каша", difficulty: 1, category: "їжа" },
  { word: "борщ", difficulty: 1, category: "їжа" },
  { word: "вареники", difficulty: 1, category: "їжа" },
  { word: "сало", difficulty: 1, category: "їжа" },
  { word: "ковбаса", difficulty: 1, category: "їжа" },
  { word: "пиріг", difficulty: 1, category: "їжа" },
  { word: "чай", difficulty: 1, category: "їжа" },
  { word: "кава", difficulty: 1, category: "їжа" },
  { word: "сік", difficulty: 1, category: "їжа" },
  { word: "вода", difficulty: 1, category: "їжа" },
  { word: "цукор", difficulty: 1, category: "їжа" },
  { word: "сіль", difficulty: 1, category: "їжа" },
  { word: "перець", difficulty: 1, category: "їжа" },
  { word: "мед", difficulty: 1, category: "їжа" },
  { word: "горіх", difficulty: 1, category: "їжа" },
  { word: "виноград", difficulty: 1, category: "їжа" },
  { word: "полуниця", difficulty: 1, category: "їжа" },
  { word: "кавун", difficulty: 1, category: "їжа" },
  { word: "диня", difficulty: 1, category: "їжа" },
  { word: "вишня", difficulty: 1, category: "їжа" },
  { word: "слива", difficulty: 1, category: "їжа" },
  { word: "груша", difficulty: 1, category: "їжа" },
  { word: "лимон", difficulty: 1, category: "їжа" },
  { word: "гриб", difficulty: 1, category: "їжа" },
  { word: "рис", difficulty: 1, category: "їжа" },
  { word: "макарони", difficulty: 1, category: "їжа" },
  { word: "піца", difficulty: 1, category: "їжа" },
  { word: "сосиска", difficulty: 1, category: "їжа" },
  { word: "млинець", difficulty: 1, category: "їжа" },

  // Objects / Home (предмети)
  { word: "стіл", difficulty: 1, category: "предмети" },
  { word: "стілець", difficulty: 1, category: "предмети" },
  { word: "ліжко", difficulty: 1, category: "предмети" },
  { word: "двері", difficulty: 1, category: "предмети" },
  { word: "вікно", difficulty: 1, category: "предмети" },
  { word: "книга", difficulty: 1, category: "предмети" },
  { word: "ручка", difficulty: 1, category: "предмети" },
  { word: "олівець", difficulty: 1, category: "предмети" },
  { word: "зошит", difficulty: 1, category: "предмети" },
  { word: "телефон", difficulty: 1, category: "предмети" },
  { word: "годинник", difficulty: 1, category: "предмети" },
  { word: "ключ", difficulty: 1, category: "предмети" },
  { word: "замок", difficulty: 1, category: "предмети" },
  { word: "лампа", difficulty: 1, category: "предмети" },
  { word: "дзеркало", difficulty: 1, category: "предмети" },
  { word: "чашка", difficulty: 1, category: "предмети" },
  { word: "тарілка", difficulty: 1, category: "предмети" },
  { word: "ложка", difficulty: 1, category: "предмети" },
  { word: "виделка", difficulty: 1, category: "предмети" },
  { word: "ніж", difficulty: 1, category: "предмети" },
  { word: "подушка", difficulty: 1, category: "предмети" },
  { word: "ковдра", difficulty: 1, category: "предмети" },
  { word: "рушник", difficulty: 1, category: "предмети" },
  { word: "мило", difficulty: 1, category: "предмети" },
  { word: "щітка", difficulty: 1, category: "предмети" },
  { word: "гребінець", difficulty: 1, category: "предмети" },
  { word: "парасолька", difficulty: 1, category: "предмети" },
  { word: "валіза", difficulty: 1, category: "предмети" },
  { word: "сумка", difficulty: 1, category: "предмети" },
  { word: "гаманець", difficulty: 1, category: "предмети" },
  { word: "окуляри", difficulty: 1, category: "предмети" },
  { word: "холодильник", difficulty: 1, category: "предмети" },
  { word: "плита", difficulty: 1, category: "предмети" },
  { word: "пральна машина", difficulty: 1, category: "предмети" },
  { word: "телевізор", difficulty: 1, category: "предмети" },
  { word: "комп'ютер", difficulty: 1, category: "предмети" },
  { word: "ножиці", difficulty: 1, category: "предмети" },
  { word: "голка", difficulty: 1, category: "предмети" },
  { word: "нитка", difficulty: 1, category: "предмети" },
  { word: "свічка", difficulty: 1, category: "предмети" },
  { word: "коробка", difficulty: 1, category: "предмети" },
  { word: "пакет", difficulty: 1, category: "предмети" },
  { word: "відро", difficulty: 1, category: "предмети" },
  { word: "мітла", difficulty: 1, category: "предмети" },
  { word: "праска", difficulty: 1, category: "предмети" },
  { word: "пилосос", difficulty: 1, category: "предмети" },

  // Nature (природа)
  { word: "сонце", difficulty: 1, category: "природа" },
  { word: "місяць", difficulty: 1, category: "природа" },
  { word: "зірка", difficulty: 1, category: "природа" },
  { word: "небо", difficulty: 1, category: "природа" },
  { word: "хмара", difficulty: 1, category: "природа" },
  { word: "дощ", difficulty: 1, category: "природа" },
  { word: "сніг", difficulty: 1, category: "природа" },
  { word: "вітер", difficulty: 1, category: "природа" },
  { word: "море", difficulty: 1, category: "природа" },
  { word: "річка", difficulty: 1, category: "природа" },
  { word: "озеро", difficulty: 1, category: "природа" },
  { word: "гора", difficulty: 1, category: "природа" },
  { word: "ліс", difficulty: 1, category: "природа" },
  { word: "дерево", difficulty: 1, category: "природа" },
  { word: "квітка", difficulty: 1, category: "природа" },
  { word: "трава", difficulty: 1, category: "природа" },
  { word: "камінь", difficulty: 1, category: "природа" },
  { word: "пісок", difficulty: 1, category: "природа" },
  { word: "земля", difficulty: 1, category: "природа" },
  { word: "вогонь", difficulty: 1, category: "природа" },
  { word: "лід", difficulty: 1, category: "природа" },
  { word: "райдуга", difficulty: 1, category: "природа" },
  { word: "блискавка", difficulty: 1, category: "природа" },
  { word: "грім", difficulty: 1, category: "природа" },
  { word: "туман", difficulty: 1, category: "природа" },
  { word: "роса", difficulty: 1, category: "природа" },
  { word: "листок", difficulty: 1, category: "природа" },
  { word: "гілка", difficulty: 1, category: "природа" },
  { word: "корінь", difficulty: 1, category: "природа" },
  { word: "берег", difficulty: 1, category: "природа" },

  // Body (тіло)
  { word: "голова", difficulty: 1, category: "тіло" },
  { word: "рука", difficulty: 1, category: "тіло" },
  { word: "нога", difficulty: 1, category: "тіло" },
  { word: "око", difficulty: 1, category: "тіло" },
  { word: "вухо", difficulty: 1, category: "тіло" },
  { word: "ніс", difficulty: 1, category: "тіло" },
  { word: "рот", difficulty: 1, category: "тіло" },
  { word: "зуб", difficulty: 1, category: "тіло" },
  { word: "волосся", difficulty: 1, category: "тіло" },
  { word: "палець", difficulty: 1, category: "тіло" },
  { word: "серце", difficulty: 1, category: "тіло" },
  { word: "кров", difficulty: 1, category: "тіло" },
  { word: "шия", difficulty: 1, category: "тіло" },
  { word: "спина", difficulty: 1, category: "тіло" },
  { word: "живіт", difficulty: 1, category: "тіло" },

  // Clothes (одяг)
  { word: "шапка", difficulty: 1, category: "одяг" },
  { word: "куртка", difficulty: 1, category: "одяг" },
  { word: "штани", difficulty: 1, category: "одяг" },
  { word: "сукня", difficulty: 1, category: "одяг" },
  { word: "черевики", difficulty: 1, category: "одяг" },
  { word: "шкарпетки", difficulty: 1, category: "одяг" },
  { word: "рукавиці", difficulty: 1, category: "одяг" },
  { word: "шарф", difficulty: 1, category: "одяг" },
  { word: "окуляри", difficulty: 1, category: "одяг" },
  { word: "футболка", difficulty: 1, category: "одяг" },
  { word: "светр", difficulty: 1, category: "одяг" },
  { word: "пальто", difficulty: 1, category: "одяг" },
  { word: "спідниця", difficulty: 1, category: "одяг" },
  { word: "краватка", difficulty: 1, category: "одяг" },
  { word: "ремінь", difficulty: 1, category: "одяг" },

  // Transport (транспорт)
  { word: "машина", difficulty: 1, category: "транспорт" },
  { word: "автобус", difficulty: 1, category: "транспорт" },
  { word: "потяг", difficulty: 1, category: "транспорт" },
  { word: "літак", difficulty: 1, category: "транспорт" },
  { word: "велосипед", difficulty: 1, category: "транспорт" },
  { word: "корабель", difficulty: 1, category: "транспорт" },
  { word: "мотоцикл", difficulty: 1, category: "транспорт" },
  { word: "трамвай", difficulty: 1, category: "транспорт" },
  { word: "таксі", difficulty: 1, category: "транспорт" },
  { word: "метро", difficulty: 1, category: "транспорт" },
  { word: "ракета", difficulty: 1, category: "транспорт" },
  { word: "гелікоптер", difficulty: 1, category: "транспорт" },
  { word: "трактор", difficulty: 1, category: "транспорт" },
  { word: "човен", difficulty: 1, category: "транспорт" },
  { word: "санки", difficulty: 1, category: "транспорт" },

  // Places (місця)
  { word: "дім", difficulty: 1, category: "місця" },
  { word: "школа", difficulty: 1, category: "місця" },
  { word: "лікарня", difficulty: 1, category: "місця" },
  { word: "магазин", difficulty: 1, category: "місця" },
  { word: "парк", difficulty: 1, category: "місця" },
  { word: "вулиця", difficulty: 1, category: "місця" },
  { word: "міст", difficulty: 1, category: "місця" },
  { word: "церква", difficulty: 1, category: "місця" },
  { word: "аптека", difficulty: 1, category: "місця" },
  { word: "бібліотека", difficulty: 1, category: "місця" },
  { word: "кухня", difficulty: 1, category: "місця" },
  { word: "ванна", difficulty: 1, category: "місця" },
  { word: "балкон", difficulty: 1, category: "місця" },
  { word: "підвал", difficulty: 1, category: "місця" },
  { word: "дах", difficulty: 1, category: "місця" },
  { word: "город", difficulty: 1, category: "місця" },
  { word: "пляж", difficulty: 1, category: "місця" },
  { word: "базар", difficulty: 1, category: "місця" },
  { word: "стадіон", difficulty: 1, category: "місця" },
  { word: "кінотеатр", difficulty: 1, category: "місця" },

  // People / Family (люди)
  { word: "мама", difficulty: 1, category: "люди" },
  { word: "тато", difficulty: 1, category: "люди" },
  { word: "бабуся", difficulty: 1, category: "люди" },
  { word: "дідусь", difficulty: 1, category: "люди" },
  { word: "дитина", difficulty: 1, category: "люди" },
  { word: "лікар", difficulty: 1, category: "люди" },
  { word: "вчитель", difficulty: 1, category: "люди" },
  { word: "поліцейський", difficulty: 1, category: "люди" },
  { word: "пожежник", difficulty: 1, category: "люди" },
  { word: "кухар", difficulty: 1, category: "люди" },
  { word: "водій", difficulty: 1, category: "люди" },
  { word: "продавець", difficulty: 1, category: "люди" },
  { word: "сусід", difficulty: 1, category: "люди" },
  { word: "друг", difficulty: 1, category: "люди" },
  { word: "король", difficulty: 1, category: "люди" },

  // Actions / Verbs (дії) — easy

  // More easy words (різне)
  { word: "прапор", difficulty: 1, category: "предмети" },
  { word: "м'яч", difficulty: 1, category: "предмети" },
  { word: "іграшка", difficulty: 1, category: "предмети" },
  { word: "лялька", difficulty: 1, category: "предмети" },
  { word: "робот", difficulty: 1, category: "предмети" },
  { word: "барабан", difficulty: 1, category: "предмети" },
  { word: "гітара", difficulty: 1, category: "предмети" },
  { word: "піаніно", difficulty: 1, category: "предмети" },
  { word: "скрипка", difficulty: 1, category: "предмети" },
  { word: "фотоапарат", difficulty: 1, category: "предмети" },
  { word: "драбина", difficulty: 1, category: "предмети" },
  { word: "молоток", difficulty: 1, category: "предмети" },
  { word: "цвях", difficulty: 1, category: "предмети" },
  { word: "пила", difficulty: 1, category: "предмети" },
  { word: "лопата", difficulty: 1, category: "предмети" },
  { word: "весло", difficulty: 1, category: "предмети" },
  { word: "намет", difficulty: 1, category: "предмети" },
  { word: "рюкзак", difficulty: 1, category: "предмети" },
  { word: "ліхтар", difficulty: 1, category: "предмети" },
  { word: "компас", difficulty: 1, category: "предмети" },

  // Colors, shapes, time (easy)
  { word: "червоний", difficulty: 1, category: "кольори" },
  { word: "синій", difficulty: 1, category: "кольори" },
  { word: "зелений", difficulty: 1, category: "кольори" },
  { word: "жовтий", difficulty: 1, category: "кольори" },
  { word: "білий", difficulty: 1, category: "кольори" },
  { word: "чорний", difficulty: 1, category: "кольори" },
  { word: "коло", difficulty: 1, category: "форми" },
  { word: "квадрат", difficulty: 1, category: "форми" },
  { word: "трикутник", difficulty: 1, category: "форми" },
  { word: "ранок", difficulty: 1, category: "час" },
  { word: "вечір", difficulty: 1, category: "час" },
  { word: "ніч", difficulty: 1, category: "час" },
  { word: "зима", difficulty: 1, category: "час" },
  { word: "літо", difficulty: 1, category: "час" },
  { word: "весна", difficulty: 1, category: "час" },
  { word: "осінь", difficulty: 1, category: "час" },

  // More easy nouns
  { word: "подарунок", difficulty: 1, category: "предмети" },
  { word: "листівка", difficulty: 1, category: "предмети" },
  { word: "конверт", difficulty: 1, category: "предмети" },
  { word: "газета", difficulty: 1, category: "предмети" },
  { word: "журнал", difficulty: 1, category: "предмети" },
  { word: "картина", difficulty: 1, category: "предмети" },
  { word: "килим", difficulty: 1, category: "предмети" },
  { word: "шафа", difficulty: 1, category: "предмети" },
  { word: "диван", difficulty: 1, category: "предмети" },
  { word: "крісло", difficulty: 1, category: "предмети" },
  { word: "полиця", difficulty: 1, category: "предмети" },
  { word: "кран", difficulty: 1, category: "предмети" },
  { word: "батарея", difficulty: 1, category: "предмети" },
  { word: "підлога", difficulty: 1, category: "предмети" },
  { word: "стеля", difficulty: 1, category: "предмети" },
  { word: "стіна", difficulty: 1, category: "предмети" },
  { word: "сходи", difficulty: 1, category: "предмети" },
  { word: "ліфт", difficulty: 1, category: "предмети" },
  { word: "паркан", difficulty: 1, category: "предмети" },
  { word: "ворота", difficulty: 1, category: "предмети" },

  // ========================================
  // LEVEL 2 — MEDIUM (~700 words)
  // Less common words, some abstract
  // ========================================

  // Professions (професії)
  { word: "архітектор", difficulty: 2, category: "професії" },
  { word: "журналіст", difficulty: 2, category: "професії" },
  { word: "програміст", difficulty: 2, category: "професії" },
  { word: "космонавт", difficulty: 2, category: "професії" },
  { word: "археолог", difficulty: 2, category: "професії" },
  { word: "бухгалтер", difficulty: 2, category: "професії" },
  { word: "перекладач", difficulty: 2, category: "професії" },
  { word: "фотограф", difficulty: 2, category: "професії" },
  { word: "скульптор", difficulty: 2, category: "професії" },
  { word: "ветеринар", difficulty: 2, category: "професії" },
  { word: "пілот", difficulty: 2, category: "професії" },
  { word: "детектив", difficulty: 2, category: "професії" },
  { word: "дипломат", difficulty: 2, category: "професії" },
  { word: "режисер", difficulty: 2, category: "професії" },
  { word: "диригент", difficulty: 2, category: "професії" },
  { word: "стоматолог", difficulty: 2, category: "професії" },
  { word: "фармацевт", difficulty: 2, category: "професії" },
  { word: "адвокат", difficulty: 2, category: "професії" },
  { word: "суддя", difficulty: 2, category: "професії" },
  { word: "хірург", difficulty: 2, category: "професії" },

  // Animals (medium)
  { word: "хамелеон", difficulty: 2, category: "тварини" },
  { word: "фламінго", difficulty: 2, category: "тварини" },
  { word: "пелікан", difficulty: 2, category: "тварини" },
  { word: "пінгвін", difficulty: 2, category: "тварини" },
  { word: "горила", difficulty: 2, category: "тварини" },
  { word: "гепард", difficulty: 2, category: "тварини" },
  { word: "носоріг", difficulty: 2, category: "тварини" },
  { word: "бегемот", difficulty: 2, category: "тварини" },
  { word: "скорпіон", difficulty: 2, category: "тварини" },
  { word: "кенгуру", difficulty: 2, category: "тварини" },
  { word: "шимпанзе", difficulty: 2, category: "тварини" },
  { word: "колібрі", difficulty: 2, category: "тварини" },
  { word: "саламандра", difficulty: 2, category: "тварини" },
  { word: "восьминіг", difficulty: 2, category: "тварини" },
  { word: "медуза", difficulty: 2, category: "тварини" },
  { word: "морська зірка", difficulty: 2, category: "тварини" },
  { word: "крабик", difficulty: 2, category: "тварини" },
  { word: "павич", difficulty: 2, category: "тварини" },
  { word: "лелека", difficulty: 2, category: "тварини" },
  { word: "яструб", difficulty: 2, category: "тварини" },

  // Food (medium)
  { word: "ананас", difficulty: 2, category: "їжа" },
  { word: "авокадо", difficulty: 2, category: "їжа" },
  { word: "манго", difficulty: 2, category: "їжа" },
  { word: "імбир", difficulty: 2, category: "їжа" },
  { word: "кориця", difficulty: 2, category: "їжа" },
  { word: "шоколад", difficulty: 2, category: "їжа" },
  { word: "марципан", difficulty: 2, category: "їжа" },
  { word: "круасан", difficulty: 2, category: "їжа" },
  { word: "еклер", difficulty: 2, category: "їжа" },
  { word: "желе", difficulty: 2, category: "їжа" },
  { word: "мармелад", difficulty: 2, category: "їжа" },
  { word: "карамель", difficulty: 2, category: "їжа" },
  { word: "бульйон", difficulty: 2, category: "їжа" },
  { word: "рагу", difficulty: 2, category: "їжа" },
  { word: "шашлик", difficulty: 2, category: "їжа" },
  { word: "холодець", difficulty: 2, category: "їжа" },
  { word: "деруни", difficulty: 2, category: "їжа" },
  { word: "голубці", difficulty: 2, category: "їжа" },
  { word: "пампушки", difficulty: 2, category: "їжа" },
  { word: "галушки", difficulty: 2, category: "їжа" },

  // Nature / Geography (medium)
  { word: "водоспад", difficulty: 2, category: "природа" },
  { word: "вулкан", difficulty: 2, category: "природа" },
  { word: "пустеля", difficulty: 2, category: "природа" },
  { word: "джунглі", difficulty: 2, category: "природа" },
  { word: "айсберг", difficulty: 2, category: "природа" },
  { word: "печера", difficulty: 2, category: "природа" },
  { word: "ущелина", difficulty: 2, category: "природа" },
  { word: "болото", difficulty: 2, category: "природа" },
  { word: "оазис", difficulty: 2, category: "природа" },
  { word: "лавина", difficulty: 2, category: "природа" },
  { word: "цунамі", difficulty: 2, category: "природа" },
  { word: "торнадо", difficulty: 2, category: "природа" },
  { word: "землетрус", difficulty: 2, category: "природа" },
  { word: "затемнення", difficulty: 2, category: "природа" },
  { word: "комета", difficulty: 2, category: "природа" },
  { word: "сузір'я", difficulty: 2, category: "природа" },
  { word: "горизонт", difficulty: 2, category: "природа" },
  { word: "рівнина", difficulty: 2, category: "природа" },
  { word: "острів", difficulty: 2, category: "природа" },
  { word: "півострів", difficulty: 2, category: "природа" },

  // Actions (medium)

  // Culture / Entertainment (medium)
  { word: "карнавал", difficulty: 2, category: "культура" },
  { word: "фестиваль", difficulty: 2, category: "культура" },
  { word: "цирк", difficulty: 2, category: "культура" },
  { word: "опера", difficulty: 2, category: "культура" },
  { word: "балет", difficulty: 2, category: "культура" },
  { word: "концерт", difficulty: 2, category: "культура" },
  { word: "вистава", difficulty: 2, category: "культура" },
  { word: "виставка", difficulty: 2, category: "культура" },
  { word: "сценарій", difficulty: 2, category: "культура" },
  { word: "п'єса", difficulty: 2, category: "культура" },
  { word: "легенда", difficulty: 2, category: "культура" },
  { word: "казка", difficulty: 2, category: "культура" },
  { word: "головоломка", difficulty: 2, category: "культура" },
  { word: "маскарад", difficulty: 2, category: "культура" },
  { word: "лотерея", difficulty: 2, category: "культура" },
  { word: "турнір", difficulty: 2, category: "культура" },
  { word: "олімпіада", difficulty: 2, category: "культура" },
  { word: "симфонія", difficulty: 2, category: "культура" },
  { word: "мюзикл", difficulty: 2, category: "культура" },
  { word: "комедія", difficulty: 2, category: "культура" },

  // Sports (medium)
  { word: "баскетбол", difficulty: 2, category: "спорт" },
  { word: "волейбол", difficulty: 2, category: "спорт" },
  { word: "теніс", difficulty: 2, category: "спорт" },
  { word: "хокей", difficulty: 2, category: "спорт" },
  { word: "бокс", difficulty: 2, category: "спорт" },
  { word: "гімнастика", difficulty: 2, category: "спорт" },
  { word: "серфінг", difficulty: 2, category: "спорт" },
  { word: "парашут", difficulty: 2, category: "спорт" },
  { word: "марафон", difficulty: 2, category: "спорт" },
  { word: "регата", difficulty: 2, category: "спорт" },
  { word: "фехтування", difficulty: 2, category: "спорт" },
  { word: "стрільба", difficulty: 2, category: "спорт" },
  { word: "шахи", difficulty: 2, category: "спорт" },
  { word: "дартс", difficulty: 2, category: "спорт" },
  { word: "скелетон", difficulty: 2, category: "спорт" },

  // Objects (medium)
  { word: "телескоп", difficulty: 2, category: "предмети" },
  { word: "мікроскоп", difficulty: 2, category: "предмети" },
  { word: "термометр", difficulty: 2, category: "предмети" },
  { word: "акваріум", difficulty: 2, category: "предмети" },
  { word: "глобус", difficulty: 2, category: "предмети" },
  { word: "скарбничка", difficulty: 2, category: "предмети" },
  { word: "кальку\u043Bятор", difficulty: 2, category: "предмети" },
  { word: "навушники", difficulty: 2, category: "предмети" },
  { word: "мікрофон", difficulty: 2, category: "предмети" },
  { word: "конвеєр", difficulty: 2, category: "предмети" },
  { word: "генератор", difficulty: 2, category: "предмети" },
  { word: "катапульта", difficulty: 2, category: "предмети" },
  { word: "маятник", difficulty: 2, category: "предмети" },
  { word: "перископ", difficulty: 2, category: "предмети" },
  { word: "штурвал", difficulty: 2, category: "предмети" },
  { word: "якір", difficulty: 2, category: "предмети" },
  { word: "компас", difficulty: 2, category: "предмети" },
  { word: "сирена", difficulty: 2, category: "предмети" },
  { word: "семафор", difficulty: 2, category: "предмети" },
  { word: "барометр", difficulty: 2, category: "предмети" },

  // More medium concepts
  { word: "рецепт", difficulty: 2, category: "різне" },
  { word: "експеримент", difficulty: 2, category: "різне" },
  { word: "традиція", difficulty: 2, category: "різне" },
  { word: "ярмарок", difficulty: 2, category: "різне" },
  { word: "скарб", difficulty: 2, category: "різне" },
  { word: "пригода", difficulty: 2, category: "різне" },
  { word: "загадка", difficulty: 2, category: "різне" },
  { word: "винахід", difficulty: 2, category: "різне" },
  { word: "портрет", difficulty: 2, category: "різне" },
  { word: "мозаїка", difficulty: 2, category: "різне" },
  { word: "каліграфія", difficulty: 2, category: "різне" },
  { word: "ілюзія", difficulty: 2, category: "різне" },
  { word: "карикатура", difficulty: 2, category: "різне" },
  { word: "граніт", difficulty: 2, category: "різне" },
  { word: "кришталь", difficulty: 2, category: "різне" },
  { word: "порцеляна", difficulty: 2, category: "різне" },
  { word: "бурштин", difficulty: 2, category: "різне" },
  { word: "корал", difficulty: 2, category: "різне" },
  { word: "фонтан", difficulty: 2, category: "різне" },
  { word: "лабіринт", difficulty: 2, category: "різне" },
  { word: "калейдоскоп", difficulty: 2, category: "різне" },
  { word: "маяк", difficulty: 2, category: "різне" },
  { word: "акведук", difficulty: 2, category: "різне" },
  { word: "обеліск", difficulty: 2, category: "різне" },
  { word: "піраміда", difficulty: 2, category: "різне" },
  { word: "амфітеатр", difficulty: 2, category: "різне" },
  { word: "колізей", difficulty: 2, category: "різне" },
  { word: "катедра", difficulty: 2, category: "різне" },
  { word: "годівниця", difficulty: 2, category: "різне" },
  { word: "шпаківня", difficulty: 2, category: "різне" },

  // Medium historical/mythical
  { word: "лицар", difficulty: 2, category: "історія" },
  { word: "козак", difficulty: 2, category: "історія" },
  { word: "гетьман", difficulty: 2, category: "історія" },
  { word: "фараон", difficulty: 2, category: "історія" },
  { word: "самурай", difficulty: 2, category: "історія" },
  { word: "гладіатор", difficulty: 2, category: "історія" },
  { word: "вікінг", difficulty: 2, category: "історія" },
  { word: "пірат", difficulty: 2, category: "історія" },
  { word: "чарівник", difficulty: 2, category: "історія" },
  { word: "русалка", difficulty: 2, category: "історія" },
  { word: "дракон", difficulty: 2, category: "історія" },
  { word: "єдиноріг", difficulty: 2, category: "історія" },
  { word: "кентавр", difficulty: 2, category: "історія" },
  { word: "фенікс", difficulty: 2, category: "історія" },
  { word: "грифон", difficulty: 2, category: "історія" },

  // ========================================
  // LEVEL 3 — HARD (~600 words)
  // Abstract concepts, rare words
  // ========================================

  // Abstract concepts
  { word: "філософія", difficulty: 3, category: "абстрактні" },
  { word: "демократія", difficulty: 3, category: "абстрактні" },
  { word: "бюрократія", difficulty: 3, category: "абстрактні" },
  { word: "аристократія", difficulty: 3, category: "абстрактні" },
  { word: "ностальгія", difficulty: 3, category: "абстрактні" },
  { word: "ентузіазм", difficulty: 3, category: "абстрактні" },
  { word: "парадокс", difficulty: 3, category: "абстрактні" },
  { word: "метафора", difficulty: 3, category: "абстрактні" },
  { word: "гіпотеза", difficulty: 3, category: "абстрактні" },
  { word: "синхронізація", difficulty: 3, category: "абстрактні" },
  { word: "інтуїція", difficulty: 3, category: "абстрактні" },
  { word: "харизма", difficulty: 3, category: "абстрактні" },
  { word: "амбіція", difficulty: 3, category: "абстрактні" },
  { word: "прокрастинація", difficulty: 3, category: "абстрактні" },
  { word: "меланхолія", difficulty: 3, category: "абстрактні" },
  { word: "ейфорія", difficulty: 3, category: "абстрактні" },
  { word: "клаустрофобія", difficulty: 3, category: "абстрактні" },
  { word: "дипломатія", difficulty: 3, category: "абстрактні" },
  { word: "ідеологія", difficulty: 3, category: "абстрактні" },
  { word: "утопія", difficulty: 3, category: "абстрактні" },
  { word: "анархія", difficulty: 3, category: "абстрактні" },
  { word: "пропаганда", difficulty: 3, category: "абстрактні" },
  { word: "цензура", difficulty: 3, category: "абстрактні" },
  { word: "абстракція", difficulty: 3, category: "абстрактні" },
  { word: "конформізм", difficulty: 3, category: "абстрактні" },
  { word: "альтруїзм", difficulty: 3, category: "абстрактні" },
  { word: "егоїзм", difficulty: 3, category: "абстрактні" },
  { word: "скептицизм", difficulty: 3, category: "абстрактні" },
  { word: "оптимізм", difficulty: 3, category: "абстрактні" },
  { word: "песимізм", difficulty: 3, category: "абстрактні" },
  { word: "сарказм", difficulty: 3, category: "абстрактні" },
  { word: "антагонізм", difficulty: 3, category: "абстрактні" },
  { word: "плагіат", difficulty: 3, category: "абстрактні" },
  { word: "імпровізація", difficulty: 3, category: "абстрактні" },
  { word: "маніпуляція", difficulty: 3, category: "абстрактні" },

  // Science / Technology (hard)
  { word: "гравітація", difficulty: 3, category: "наука" },
  { word: "фотосинтез", difficulty: 3, category: "наука" },
  { word: "еволюція", difficulty: 3, category: "наука" },
  { word: "термодинаміка", difficulty: 3, category: "наука" },
  { word: "електромагніт", difficulty: 3, category: "наука" },
  { word: "антибіотик", difficulty: 3, category: "наука" },
  { word: "хромосома", difficulty: 3, category: "наука" },
  { word: "мітохондрія", difficulty: 3, category: "наука" },
  { word: "нейрон", difficulty: 3, category: "наука" },
  { word: "квантовий", difficulty: 3, category: "наука" },
  { word: "алгоритм", difficulty: 3, category: "наука" },
  { word: "кібернетика", difficulty: 3, category: "наука" },
  { word: "біометрія", difficulty: 3, category: "наука" },
  { word: "голограма", difficulty: 3, category: "наука" },
  { word: "нанотехнологія", difficulty: 3, category: "наука" },
  { word: "ультразвук", difficulty: 3, category: "наука" },
  { word: "рентген", difficulty: 3, category: "наука" },
  { word: "стетоскоп", difficulty: 3, category: "наука" },
  { word: "каталізатор", difficulty: 3, category: "наука" },
  { word: "осмос", difficulty: 3, category: "наука" },

  // Hard actions / verbs

  // Culture / Arts (hard)
  { word: "ренесанс", difficulty: 3, category: "культура" },
  { word: "авангард", difficulty: 3, category: "культура" },
  { word: "сюрреалізм", difficulty: 3, category: "культура" },
  { word: "імпресіонізм", difficulty: 3, category: "культура" },
  { word: "кубізм", difficulty: 3, category: "культура" },
  { word: "мінімалізм", difficulty: 3, category: "культура" },
  { word: "романтизм", difficulty: 3, category: "культура" },
  { word: "класицизм", difficulty: 3, category: "культура" },
  { word: "бароко", difficulty: 3, category: "культура" },
  { word: "готика", difficulty: 3, category: "культура" },
  { word: "модернізм", difficulty: 3, category: "культура" },
  { word: "футуризм", difficulty: 3, category: "культура" },
  { word: "експресіонізм", difficulty: 3, category: "культура" },
  { word: "конструктивізм", difficulty: 3, category: "культура" },
  { word: "деконструкція", difficulty: 3, category: "культура" },
  { word: "каліграфія", difficulty: 3, category: "культура" },
  { word: "антиквар", difficulty: 3, category: "культура" },
  { word: "палеонтологія", difficulty: 3, category: "культура" },
  { word: "археологія", difficulty: 3, category: "культура" },
  { word: "етнографія", difficulty: 3, category: "культура" },

  // Complex / rare objects
  { word: "саксофон", difficulty: 3, category: "предмети" },
  { word: "акордеон", difficulty: 3, category: "предмети" },
  { word: "контрабас", difficulty: 3, category: "предмети" },
  { word: "ксилофон", difficulty: 3, category: "предмети" },
  { word: "віолончель", difficulty: 3, category: "предмети" },
  { word: "гобелен", difficulty: 3, category: "предмети" },
  { word: "канделябр", difficulty: 3, category: "предмети" },
  { word: "секстант", difficulty: 3, category: "предмети" },
  { word: "астролябія", difficulty: 3, category: "предмети" },
  { word: "пергамент", difficulty: 3, category: "предмети" },
  { word: "монокль", difficulty: 3, category: "предмети" },
  { word: "епілет", difficulty: 3, category: "предмети" },
  { word: "капюшон", difficulty: 3, category: "предмети" },
  { word: "транзистор", difficulty: 3, category: "предмети" },
  { word: "осцилограф", difficulty: 3, category: "предмети" },

  // Complex nature / geography
  { word: "архіпелаг", difficulty: 3, category: "природа" },
  { word: "біосфера", difficulty: 3, category: "природа" },
  { word: "стратосфера", difficulty: 3, category: "природа" },
  { word: "тропосфера", difficulty: 3, category: "природа" },
  { word: "магнітосфера", difficulty: 3, category: "природа" },
  { word: "екосистема", difficulty: 3, category: "природа" },
  { word: "мікроклімат", difficulty: 3, category: "природа" },
  { word: "пермафрост", difficulty: 3, category: "природа" },
  { word: "геотермальний", difficulty: 3, category: "природа" },
  { word: "ерозія", difficulty: 3, category: "природа" },
  { word: "тектоніка", difficulty: 3, category: "природа" },
  { word: "седиментація", difficulty: 3, category: "природа" },
  { word: "конденсація", difficulty: 3, category: "природа" },
  { word: "фотоелемент", difficulty: 3, category: "природа" },
  { word: "сублімація", difficulty: 3, category: "природа" },

  // Hard historical / mythical
  { word: "інквізиція", difficulty: 3, category: "історія" },
  { word: "реформація", difficulty: 3, category: "історія" },
  { word: "просвітництво", difficulty: 3, category: "історія" },
  { word: "абсолютизм", difficulty: 3, category: "історія" },
  { word: "колоніалізм", difficulty: 3, category: "історія" },
  { word: "імперіалізм", difficulty: 3, category: "історія" },
  { word: "феодалізм", difficulty: 3, category: "історія" },
  { word: "меркантилізм", difficulty: 3, category: "історія" },
  { word: "індустріалізація", difficulty: 3, category: "історія" },
  { word: "глобалізація", difficulty: 3, category: "історія" },
  { word: "урбанізація", difficulty: 3, category: "історія" },
  { word: "колонізація", difficulty: 3, category: "історія" },
  { word: "анексія", difficulty: 3, category: "історія" },
  { word: "конфедерація", difficulty: 3, category: "історія" },
  { word: "суверенітет", difficulty: 3, category: "історія" },

  // More hard abstract / philosophy
  { word: "екзистенціалізм", difficulty: 3, category: "абстрактні" },
  { word: "детермінізм", difficulty: 3, category: "абстрактні" },
  { word: "релятивізм", difficulty: 3, category: "абстрактні" },
  { word: "прагматизм", difficulty: 3, category: "абстрактні" },
  { word: "нігілізм", difficulty: 3, category: "абстрактні" },
  { word: "гедонізм", difficulty: 3, category: "абстрактні" },
  { word: "аскетизм", difficulty: 3, category: "абстрактні" },
  { word: "фаталізм", difficulty: 3, category: "абстрактні" },
  { word: "містицизм", difficulty: 3, category: "абстрактні" },
  { word: "раціоналізм", difficulty: 3, category: "абстрактні" },
  { word: "емпіризм", difficulty: 3, category: "абстрактні" },
  { word: "антропоцентризм", difficulty: 3, category: "абстрактні" },
  { word: "космополітизм", difficulty: 3, category: "абстрактні" },
  { word: "меценатство", difficulty: 3, category: "абстрактні" },
  { word: "волонтерство", difficulty: 3, category: "абстрактні" },
  { word: "підприємництво", difficulty: 3, category: "абстрактні" },
  { word: "менеджмент", difficulty: 3, category: "абстрактні" },
  { word: "маркетинг", difficulty: 3, category: "абстрактні" },
  { word: "франчайзинг", difficulty: 3, category: "абстрактні" },
  { word: "аутсорсинг", difficulty: 3, category: "абстрактні" },

  // Medical / Body (hard)
  { word: "анестезія", difficulty: 3, category: "наука" },
  { word: "діагностика", difficulty: 3, category: "наука" },
  { word: "реабілітація", difficulty: 3, category: "наука" },
  { word: "імунітет", difficulty: 3, category: "наука" },
  { word: "метаболізм", difficulty: 3, category: "наука" },
  { word: "адреналін", difficulty: 3, category: "наука" },
  { word: "серотонін", difficulty: 3, category: "наука" },
  { word: "гемоглобін", difficulty: 3, category: "наука" },
  { word: "ферментація", difficulty: 3, category: "наука" },
  { word: "стерилізація", difficulty: 3, category: "наука" },
  { word: "вакцинація", difficulty: 3, category: "наука" },
  { word: "трансплантація", difficulty: 3, category: "наука" },
  { word: "дефібриляція", difficulty: 3, category: "наука" },
  { word: "рефлексологія", difficulty: 3, category: "наука" },
  { word: "акупунктура", difficulty: 3, category: "наука" },

  // Tech / Modern (hard)
  { word: "криптовалюта", difficulty: 3, category: "технології" },
  { word: "блокчейн", difficulty: 3, category: "технології" },
  { word: "штучний інтелект", difficulty: 3, category: "технології" },
  { word: "віртуальна реальність", difficulty: 3, category: "технології" },
  { word: "кібербезпека", difficulty: 3, category: "технології" },
  { word: "біотехнологія", difficulty: 3, category: "технології" },
  { word: "робототехніка", difficulty: 3, category: "технології" },
  { word: "нейромережа", difficulty: 3, category: "технології" },
  { word: "дрон", difficulty: 3, category: "технології" },
  { word: "стартап", difficulty: 3, category: "технології" },
];

// Helper function to get words by difficulty
export function getWordsByDifficulty(difficulty) {
  return ukrainianWords.filter(w => w.difficulty === difficulty);
}

// Helper function to get word count stats
export function getWordStats() {
  return {
    easy: ukrainianWords.filter(w => w.difficulty === 1).length,
    medium: ukrainianWords.filter(w => w.difficulty === 2).length,
    hard: ukrainianWords.filter(w => w.difficulty === 3).length,
    total: ukrainianWords.length,
  };
}
